### ISSUE TITLE
More than 2 columns?

### ISSUE THREAD

**Issue by enemyofaverage** [andersnoren/spiekermann#1]
Hi Andres,

Loving the theme. Is there a way to make the index page have more than 2 columns? For example 3, 4, or even 5 columns wide?

I would like the feature images to be a little smaller and have more across the page.

Cheers
Craig

**Comment by andersnoren** [comment]
Hey @enemyofaverage,

Glad you like it! 

If you remove the `Asymmetrical grid` block style from the Post Template block in the Posts template part, you can set any number of columns, but the grid won't have the asymmetrical layout that it has on the Spiekermann demo site. I might add the option for more columns for the asymmetrical grid block style in the future as well.

— Anders
